version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - 5672:5672
    - 5671:5671
    - 15672:15672
   
  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here
    environment:
      - STORAGE_TYPE=mem
      - RABBIT_URI=amqp://rabbitmq
      # Uncomment to disable scribe
      # - SCRIBE_ENABLED=false
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG
    links:
      - rabbitmq
    depends_on:
    - rabbitmq
    ports:
      # Port used for the Zipkin UI and HTTP Api
    - 9411:9411
